### ISSUE TITLE
API_AddRecord action not working

### ISSUE THREAD

**Issue by krismercado** [tflanagan/php-quickbase#11] opened 2020-06-23 07:20 UTC
Could not parse XML input. XML Parsing Error. not well-formed (invalid token) at line 2 column 257 (which is byte 301)

**Comment by krismercado** [comment] 2020-06-23 07:26
I think it's because of the xml format: https://help.quickbase.com/api-guide/add_record.html#Request_Parameters

Payload:
`<qdbapi>
<dbid>{my_db_id}</dbid>
<disprec>1</disprec>
<fform></fform>
<ignoreerror></ignoreerror>
<msinutc></msinutc>
<msasdurationdefault></msasdurationdefault>
<usertoken>{my_token}</usertoken>
<encoding>ISO-8859-1</encoding>
<field><fid="7">Hello World!</fid="7"></field>
</qdbapi>`

**Comment by tflanagan** [comment] 2020-06-23 12:36
Hi @krismercado,

Are you using this library to generate that XML packet? It doesn't look like you are.

This is what is incorrect:
```xml
<field><fid="7">Hello World!</fid="7"></field>
```

It should be:
```xml
<field fid="7">Hello World!</field>
```

**Comment by krismercado** [comment] 2020-06-24 01:42
Yes, I'm using this library. i.e
`$results = $quickbase->api('API_AddRecord', array(
			    'dbid' => '{database_id}',
			    'fields' => array(
			      array( 'fid="7"' => 'Hello World!' ),
			    ),
			    'disprec' => true,
			    'fform' => false,
			    'ignoreError' => false,
			    'msInUTC' => false,
			    'msAsDurationDefault' => false
			  ));`

Do you have examples how I'm supposed to send the AddRecord event?

It's generating this still:
`<field><fid="7">Hello World!</fid="7"></field>`

**Comment by krismercado** [comment] 2020-06-24 02:27
also happens for API_EditRecord

`$results = $quickbase->api('API_EditRecord', array(
					'dbid' => '{database_id}',
					'rid' => 7,
					'fields' => array(
						array( 'fid' => 7, 'value' => 'Hello World!' )
					)
				));`

Still generates this:
`<qdbapi><dbid>{database_id}</dbid><rid>7</rid><msinutc>1</msinutc><usertoken>{user_token}</usertoken><encoding>ISO-8859-1</encoding><field><fid>7</fid><value>Hello World!</value></field></qdbapi>`

**Comment by tflanagan** [comment] 2020-06-24 13:45
Hey @krismercado,

I'm unable to reproduce this issue.

Are you handwriting that XML? It doesn't seem to be exactly what the library would produce.

What version of the library and php are you using?

**Comment by krismercado** [comment] 2020-06-24 21:19
no I'm not handwriting it. I just spit out a print_r on the library - payload to see what is being sent to quickbase.

added this code `print_r($this->payload);` in the `prepareCH` function.

I pulled the latest code from master. Php version is 5.5.9-1ubuntu4.26

I'm using codeigniter, added the library manually and loaded the file via $autoload['libraries'] = array('quickbase');

Then in a controller I call the library:
	

``` 
$quickbase = new QuickBase(array(
   'realm' => '{real_name}',
   'userToken' => {token}
));

**Comment by tflanagan** [comment] 2020-06-25 08:06
Hey @krismercado,

I'm sorry. I'm still not able to reproduce this issue.

I understand you put a `var_dump`, but from your initial report and subsequent XML packets, however, I'm still iffy that these XML packets were generated by this library. The declaration is missing and cases are inaccurate.

The only issue I see in your code snippet is this: `array( 'fid="7"' => 'Hello World!' )`

It should be `array( 'fid' => 7, 'value' => 'Hello World!' )`

This library uses `SimpleXMLElement` to build the XML packet, not much can go wrong here.

As you are using a version of PHP that is no longer supported and I'm unable to reproduce the issue, I'm going to close this issue.

I recommend upgrading PHP and looking over these resources:
https://www.php.net/migration56
https://www.php.net/migration70
https://www.php.net/migration71
https://www.php.net/migration72

**Closed as completed by tflanagan** 2020-06-25 08:06 UTC
